parent: "configs/ours_base.yaml"
save_step: 400

frame_start: 0
frame_step: 0
frame_num: -1

# dataset params:
source_path: "./data/realsense/d455f/first_room"
save_path: "output/dataset/realsense/first_room"

use_gt_pose: False
